services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  kestra:
    image: kestra/kestra:latest-full
    ports:
      - "8090:8080"  # avoid conflict with pgAdmin
    environment:
      - KESTRA_CONFIGURATION=/app/config/application.yaml
    volumes:
      - ./application.yaml:/app/config/application.yaml
      - kestra-data:/app/storage
    depends_on:
      - pgdatabase
    restart: unless-stopped

volumes:
  pgadmin_data:
  kestra-data: